# SIGNUP
@endpoint = http://localhost:3001

POST {{endpoint}}/auth/sign-up HTTP/1.1
content-type: application/json

{
    "username": "informatika",
    "fullName": "Prodi Informatika",
    "email": "informatika@gmail.com",
    "password": "informatika"
}

###

POST {{endpoint}}/auth/sign-in 
content-type: application/json

{
    "username": "udinsedunia",
    # OR
    "email": "udinsedunia2@gmail.com",
    "password": "udinganteng123"
}

###

POST {{endpoint}}/auth/sign-in 
content-type: application/json

{
    "username": "informatika",
    "password": "informatika"
}

###

GET {{endpoint}}/auth/me
content-type: application/json

###

GET {{endpoint}}/auth/log-out
content-type: application/json


###
# ADD SUB 1 BAG 1
POST {{endpoint}}/sub1/bag1
content-type: application/json

{
    "lembagaMitra" : "Universitas Malaysia Pahang",
    "tingkat" : "Internasional",
    "judulKegiatan": "Programme Summer Class",
    "manfaat": "Meningkatkan Konten pembelajaran dan meningkatkan sistem pembelajaran dosen",
    "waktuDanDurasi"  : "1 Bulan",
    "buktiKerjasama" : "Surat Tugas, undangan, Mou, photo kegiatan",
    "tahunBerakhir" : 2019
}

###
# UPDATE SUB1BAG1
PUT {{endpoint}}/sub1/bag1/62e3ff05fbcace69b52186a0
content-type: application/json

{
    "lembagaMitra" : "Universitas Indonesias",
    "tingkat" : "Internasional",
    "judulKegiatan": "Programme Summer Class",
    "manfaat": "Meningkatkan Konten pembelajaran dan meningkatkan sistem pembelajaran dosen",
    "waktuDanDurasi"  : "1 Bulan",
    "buktiKerjasama" : "Surat Tugas, undangan, Mou, photo kegiatan",
    "tahunBerakhir" : 2019
}

###

GET {{endpoint}}/sub1/bag1/
content-type: application/json
###

DELETE {{endpoint}}/sub1/bag1/62e3fbd84ca1f25f3ebbac4a
content-type: application/json

###
# ADD SUB 1 BAG 2
POST {{endpoint}}/sub1/bag2
content-type: application/json

{
    "lembagaMitra" : "Universitas Malaysia Pahang",
    "tingkat" : "Internasional",
    "judulKegiatan": "Programme Summer Class",
    "manfaat": "Meningkatkan Konten pembelajaran dan meningkatkan sistem pembelajaran dosen",
    "waktuDanDurasi"  : "1 Bulan",
    "buktiKerjasama" : "Surat Tugas, undangan, Mou, photo kegiatan",
    "tahunBerakhir" : 2019
}

###
# UPDATE SUB1BAG2
PUT {{endpoint}}/sub1/bag2/62e3ff05fbcace69b52186a0
content-type: application/json

{
    "lembagaMitra" : "Universitas Indonesias",
    "tingkat" : "Internasional",
    "judulKegiatan": "Programme Summer Class",
    "manfaat": "Meningkatkan Konten pembelajaran dan meningkatkan sistem pembelajaran dosen",
    "waktuDanDurasi"  : "1 Bulan",
    "buktiKerjasama" : "Surat Tugas, undangan, Mou, photo kegiatan",
    "tahunBerakhir" : 2019
}

###

GET {{endpoint}}/sub1/bag2/
content-type: application/json
###

DELETE {{endpoint}}/sub1/bag2/62e3fbd84ca1f25f3ebbac4a
content-type: application/json

###
# ADD SUB 2 BAG 1
POST {{endpoint}}/sub2/bag1
content-type: application/json

{
    "tahunAkademik": 2019,
    "dayaTampung": 324,
    "jumlahCalonMahasiswa": {
      "pendaftar": 345,
      "lulusSeleksi": 34
    },
    "jumlahMahasiswaBaru": {
      "reguler": 34,
      "transfer": 43
    },
    "jumlahMahasiswaAktif": {
      "reguler": 34,
      "transfer": 2
    }
  
}



###
# ADD SUB 2 BAG 2
POST {{endpoint}}/sub2/bag2
content-type: application/json

{
     "programStudi": "Sistem Informasi",
    "jumlahMahasiswaAktif": {
      "TS2": 4,
      "TS1": 45,
      "TS": 23
    },
    "jumlahMahasiswaAsingPenuhWaktu": {
      "TS2": 23,
      "TS1": 32,
      "TS": 32
    },
    "jumlahMahasiswaAsingParuhWaktu": {
      "TS2": 2,
      "TS1": 57,
      "TS": 45
    }
}

###
# ADD SUB 3 BAG A 1
POST {{endpoint}}/sub3/bagA1
content-type: application/json

{
    "namaDosen": "Dwi Romadhon",
    "nidn": "1232342343",
    "pendidikanPascaSarjana": {
      "magister": "Universitas Indonesia",
      "doktor": "Univeritar Gajah Mada"
    },
    "bidangKeahlian": "Informatika",
    "keseuaian": "Sangat Sesuai",
    "jabatanAkademik": "Ketua Prodi",
    "sertifikatPendidikProfessional": "342324325432",
    "sertifikatKompetensi": "35346243",
    "mataKuliahYangDiAmpuPadaPsAkreditasi": "Informatika",
    "kesesuaianBidangKeahlian": "Sangat Sesuai",
    "mataKuliahYangDiAmpuPadaPsLain": "Sistem Informasi"
}


###
# ADD SUB 3 BAG B 1
POST {{endpoint}}/sub3/bagB1
content-type: application/json

{
   "namaDosen": "Ahmad Cucus",
    "bidangKeahlian": "Informatika",
    "rekognisiDanBuktiPendukung": "343242342",
    "tingkat": "Nasional",
    "tahun": 2019
}
###
# ADD SUB 3 BAG B 2
POST {{endpoint}}/sub3/bagB2
content-type: application/json

{
   "sumberPembiayaan": "Pemerintah",
    "jumlahJudulPenelitian": {
      "TS2": 12,
      "TS1": 21,
      "TS": 23
    }
    # "jumlah": 123
}

###
# ADD SUB 3 BAG B 2
GET {{endpoint}}/sub3/bagB2/
content-type: application/json

###
# UPDATE SUB 3 BAG B 2
PUT {{endpoint}}/sub3/bagB2/62e621944320708b3fef619d
content-type: application/json

{
  "jumlahJudulPenelitian": {
    "TS": 1,
    "TS2": 10,
    "TS1" : 3
  }
}


###
# ADD SUB 4
POST {{endpoint}}/sub4/
content-type: application/json

{
  "jenisPenggunaan": "Biaya Operasional Pendidikan",
    "unitPengelolaanPs": {
      "TS2":  2191350000,
      "TS1":  2198550000 ,
      "TS":  2265750000 
    },
    "programStudi": {
      "TS2":  1350600000 ,
      "TS1":  1357800000,
      "TS":  1710750000 
    }
    
}

###
# GET SUB 4
GET {{endpoint}}/sub4/
content-type: application/json

###
# UPDATE SUB 4
PUT {{endpoint}}/sub4/62e62f07c2e712ff39ffc6a4
content-type: application/json

{
  "isAccepted" : true
}

